### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by th0th** [the-markup/blacklight-collector#10]
Greetings, first of all, thanks for making this library available to us all!

I have a question related to the license though. The OpenWPM seems to be licensed with GPLv3 but the code in this repository is not licensed with GPL. Doesn't GPL prevent such a re-licensing?

**Comment by samatt** [comment]
Hi there, thanks for raising this issue. Let me look into it and get back to you.

**Comment by th0th** [comment]
Thanks.
