### ISSUE TITLE
Replace "page.waitFor" with "page.waitForTimeout"

### ISSUE THREAD

**Issue by johansmith90** [the-markup/blacklight-collector#4]
Running `await.collector` currently causes a depreciation warning from puppeteer to be logged to the console every time `waitFor` is called with `puppeteer@5.2.1`.

> waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code

Replacing `page.waitFor` with `page.waitForTimeout` in the following files should remove this depreciation warning:
- src/pptr-utils/interaction-utils.ts
- src/collector.ts
- __tests__/key-logging.ts

Happy to submit a PR if you're accepting them.

**Comment by samatt** [comment]
Thanks, yeah I noticed this when I upgraded to 5.2.1, will fix on the next release

**Comment by simonft** [comment]
Fixed in #30. Thanks for the report!
