### ISSUE TITLE
Adding examples into a new folder

### ISSUE THREAD

**Issue by EvilWatermelon** [the-markup/blacklight-collector#51]
Hi,

I have written a JS file to use blacklight with MQTT and another one with a REST API call. Can I push it in an extra branch?

**Comment by simonft** [comment]
Thanks for using Blacklight and offering to contribute! We're still trying to figure out how this repository is going to relate to the hosted version we run, and this might not be the best place for scripts that interact with the version we host. But if you submit a pull request we can try to take a look. For instructions on how to do that, see [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by EvilWatermelon** [comment]
Hi, I will do this in the next few days.
