### ISSUE TITLE
Which browsers are possible to use

### ISSUE THREAD

**Issue by EvilWatermelon** [the-markup/blacklight-collector#78]
I've looked into the doc of puppeteer link and I can't find a list of devices/browsers. When passing Firefox as the `user-agent` then blacklight opens chromium? Is it possible to use different browsers or just different devices?

**Comment by simonft** [comment]
The `user-agent` of a browser identifies what the browser _claims_ to be, but it can be changed by the client without actually changing the software used to browse. The user agent parameter to blacklight just changes that string, it doesn't actually change the browser being used (which isn't currently supported). 

You can change the actual user agent string you want though. MDN has some [examples](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent). Note that the browser will still behave like Chromium.

**Comment by EvilWatermelon** [comment]
Oh ok, I see. Thanks.
